### ISSUE TITLE
Seed 0x060100700177277B40 results in silence

### ISSUE THREAD

**Issue by jaredkrinke** [DavW/autotracker#2]
The first section of 0x060100700177277B40 is completely empty (and the second section only has 1 instrument). Seems like it would be good to avoid silence.

But really, I just wanted to open this issue to say that this thing is absolutely amazing! It sounds like authentic chiptune music that would fit into an old video game just fine. The code seems so simple, but the results are just... incredible.

My favorite seed so far is: 0x0B01057006A952D080

Also enjoying this faster one: 0x0401069D09B3EB1A50

**Comment by vitling** [comment]
Because of the way the pattern enabledness is randomised independently per channel, this is actually not that surprising, and will occur 0.2% of the time: https://github.com/vitling/autotracker/blob/main/src/tracker.ts#L153-L159

Silence is - of course - not ideal but changing any of the random parts of the algorithm now would mess up the random seeding and make everyone's saved seeds produce different music; so I prefer to just think of silent patterns as breaks between pieces :-D

**Comment by jaredkrinke** [comment]
Heh, breaks, I like it.

Just for the record: I think you could just check to see if there are zero active voices and then "re-roll" in that case -- I don't think that would break existing seeds (except silent ones) because you'd just be advancing forward automatically instead of waiting.
